name: oc

on:
  - push
  - delete

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub Repository
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

   - name: Push to GitLab
    run: |
      git config --global user.name ${{ secrets.TARGET_USERNAME }}
      git remote add gitlab https://oauth2:${{ secrets.TARGET_TOKEN }}@${{ secrets.TARGET_URL }}
      git push gitlab HEAD:main
